
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #微服务路由功能(通过application.name 服务的名字来实现路由功能)
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://Cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById/**        # 断言匹配，路径相匹配的进行路由
            #- Header=X-Request-Id, [a-h]  #指定请求头Header: 其值在正则表达式成立之内可正常访问地址
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai] #在当前请求时间之后才有效果
            #- Cookie=username,zzyy   #cookie  当前网关路由地址需需接收Cookie键值对信息才可以访问路由地址


        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://Cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/getDiscovery       # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_routh3 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
            #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://Cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById     # 断言，路径相匹配的进行路由
              #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
              #- Cookie=username,zzyy
              #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


